### ISSUE TITLE
Add Search Feature or a Filter

### ISSUE THREAD

**Issue by Sahil12524** [henry-richard7/JioTV-Proxy#2]
The overall project is absolutely amazing I loved your work!, please do not discontinue the project as this is the one which is working fine!
Please add a feature of filtering of category like Music, movies, kids, news with language filters. As finding channels is a bit mess!

**Comment by henry-richard7** [comment]
I have added search feature, though the UI might be simple. Kindly check and let me know.

**Comment by Sahil12524** [comment]
The feature is good, in fact it works as intended.
need few improvement:
1. if the search is not found then it must display not result other wise it shows blank page.
2. if there is no text in search box, the search box must not activate (click able).
3. if blank search has taken place then the show all button must not be visible.

**Comment by henry-richard7** [comment]
I have made the changes.

**Comment by Sahil12524** [comment]
> I have made the changes.

Aah, nice improvements as expected. The upper navigation buttons are also fixed before they were not working. Now everything works fine. Please look into the issue for Sony channels also as they are not working.

I am closing this issue as the problem was solved!
