### ISSUE TITLE
Add OTP login System

### ISSUE THREAD

**Issue by kumaraguru1735** [henry-richard7/JioTV-Proxy#4]
Add OTP login System

**Comment by somkar1** [comment]
Unable to find/set username and password option on the JioTV, so cannot use the email and password option in this script.

**Comment by henry-richard7** [comment]
Hi,
I will try to add OTP login when I have free time.

**Comment by henry-richard7** [comment]
Added Login via OTP. Please feel free to reopen if you have any issues in using this, Thanks!
