### ISSUE TITLE
help for Linux installation

### ISSUE THREAD

**Issue by dheer99** [henry-richard7/JioTV-Proxy#6]
Please help, how can we use latest release and install it on ubuntu.
I have downloaded it (JioTV_auto_build_LINUX_x86_64.zip) in Linux server but not sure how to run it now.

**Comment by henry-richard7** [comment]
Hi,
To run in linux, go to the directory u have extracted then right-click and choose **open in terminal**
Then type chmod +x JioTV
Then type ./JioTV
