### ISSUE TITLE
pre-requisite to tun./JioTV on Linux (Ubuntu Touch)

### ISSUE THREAD

**Issue by dheer99** [henry-richard7/JioTV-Proxy#7]
Hello, as you advise earlier to run this project on Linux, I am able to run this on my Ubuntu laptop.
but not able to run it on Ubuntu Touch phone.
please advise any pre requisite for this project

example reference
Then type chmod +x JioTV
Then type ./JioTV

**Comment by henry-richard7** [comment]
If your using Ubuntu Touch, you need follow **How To Use (From Source)** .

**Comment by henry-richard7** [comment]
I am closing this ticket, feel free to open it again.
